In [11]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import matplotlib as mpl
from mpl_toolkits.mplot3d import Axes3D
from random import randint

In [12]:
datos = pd.read_csv("datos_p_1.csv", header=None)

/Users/Prueba/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2717: DtypeWarning: Columns (4,13,22) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [19]:
datos.head()

,0,1,2,3,4,5,6,7,8,9,...,21,22,23,24,25,26,27,28,29,30
0,0.003439,0.361504,0.699425,0.188906,1.395203e+00,-5.381678,-1.973678,18.37550,28.31851,9.598993,...,-0.035489,-3.756327e-02,-0.000192,-0.032795,0.123929,0.249693,-0.209245,-0.451801,0.626648,NaN
1,0.003438,0.360386,0.697348,0.182633,1.395132e+00,-5.381275,-1.971792,18.37493,28.31888,9.600118,...,-0.034512,-3.734659e-02,-0.000192,-0.032677,0.123931,0.249625,-0.209233,-0.451831,0.626313,NaN
2,0.003437,0.358666,0.695127,0.176345,1.395020e+00,-5.380869,-1.969905,18.37437,28.31924,9.601243,...,-0.033476,-3.712218e-02,-0.000192,-0.032558,0.123932,0.249557,-0.209221,-0.451862,0.625977,NaN
3,0.003436,0.356931,0.692908,0.170058,1.394909e+00,-5.380463,-1.968019,18.37380,28.31961,9.602368,...,-0.032441,-3.689785e-02,-0.000192,-0.032439,0.123934,0.249489,-0.209208,-0.451893,0.625642,NaN
4,0.003435,0.354594,0.690544,0.163755,1.394757e+00,-5.380055,-1.966132,18.37323,28.31997,9.603493,...,-0.031347,-3.666578e-02,-0.000192,-0.032320,0.123936,0.249421,-0.209197,-0.451924,0.625307,NaN

In [14]:
def index(p,dat):
    return 3*p + dat
colors = []
for i in range(10):
    colors.append('#%06X' % randint(0, 0xFFFFFF))

In [23]:
fig = plt.figure()
for p in range(10):
    ax = fig.gca(projection='3d')
    x = datos.iloc[:,index(p,0)]
    y = datos.iloc[:,index(p,1)]
    z = datos.iloc[:,index(p,2)]
    print(x,y,z)

0         0.003439
1         0.003438
2         0.003437
3         0.003436
4         0.003435
5         0.003434
6         0.003433
7         0.003432
8         0.003431
9         0.003431
10        0.003430
11        0.003429
12        0.003428
13        0.003427
14        0.003426
15        0.003425
16        0.003424
17        0.003423
18        0.003422
19        0.003421
20        0.003421
21        0.003420
22        0.003419
23        0.003418
24        0.003417
25        0.003416
26        0.003415
27        0.003414
28        0.003413
29        0.003412
            ...
249970    0.003857
249971    0.003856
249972    0.003855
249973    0.003854
249974    0.003853
249975    0.003852
249976    0.003851
249977    0.003850
249978    0.003849
249979    0.003848
249980    0.003847
249981    0.003846
249982    0.003845
249983    0.003844
249984    0.003843
249985    0.003842
249986    0.003841
249987    0.003840
249988    0.003839
249989    0.003838
249990    0.003837
249991    0.003836
249992    0.003835
249993    0.003834
249994    0.003833
249995    0.003832
249996    0.003831
249997    0.003829
249998    0.003828
249999    0.003827
Name: 0, Length: 250000, dtype: float64 0         0.361504
1         0.360386
2         0.358666
3         0.356931
4         0.354594
5         0.352228
6         0.349258
7         0.346249
8         0.342633
9         0.338973
10        0.334701
11        0.330380
12        0.325446
13        0.320463
14        0.314862
15        0.309218
16        0.302951
17        0.296649
18        0.289723
19        0.282773
20        0.275198
21        0.267613
22        0.259405
23        0.251206
24        0.242386
25        0.233598
26        0.224195
27        0.214847
28        0.204895
29        0.195025
            ...
249970    0.430213
249971    0.359490
249972    0.435381
249973    0.370017
249974    0.439862
249975    0.379974
249976    0.443644
249977    0.389347
249978    0.446715
249979    0.398120
249980    0.449064
249981    0.406281
249982    0.450679
249983    0.413814
249984    0.451549
249985    0.420706
249986    0.451663
249987    0.426945
249988    0.451013
249989    0.432517
249990    0.449587
249991    0.437410
249992    0.447377
249993    0.441611
249994    0.444374
249995    0.445109
249996    0.440569
249997    0.447891
249998    0.435956
249999    0.449946
Name: 1, Length: 250000, dtype: float64 0         0.699425
1         0.697348
2         0.695127
3         0.692908
4         0.690544
5         0.688181
6         0.685675
7         0.683172
8         0.680524
9         0.677880
10        0.675092
11        0.672309
12        0.669382
13        0.666461
14        0.663395
15        0.660337
16        0.657135
17        0.653941
18        0.650603
19        0.647275
20        0.643802
21        0.640341
22        0.636735
23        0.633143
24        0.629405
25        0.625683
26        0.621815
27        0.617964
28        0.613967
29        0.609990
            ...
249970   -0.161167
249971   -0.154887
249972   -0.146853
249973   -0.140545
249974   -0.132478
249975   -0.126144
249976   -0.118046
249977   -0.111689
249978   -0.103564
249979   -0.097187
249980   -0.089037
249981   -0.082643
249982   -0.074473
249983   -0.068064
249984   -0.059876
249985   -0.053455
249986   -0.045254
249987   -0.038822
249988   -0.030611
249989   -0.024172
249990   -0.015954
249991   -0.009511
249992   -0.001288
249993    0.005156
249994    0.013379
249995    0.019822
249996    0.028042
249997    0.034482
249998    0.042696
249999    0.049129
Name: 2, Length: 250000, dtype: float64

In [16]:
datos.iloc[:,0]

0         0.003439
1         0.003438
2         0.003437
3         0.003436
4         0.003435
5         0.003434
6         0.003433
7         0.003432
8         0.003431
9         0.003431
10        0.003430
11        0.003429
12        0.003428
13        0.003427
14        0.003426
15        0.003425
16        0.003424
17        0.003423
18        0.003422
19        0.003421
20        0.003421
21        0.003420
22        0.003419
23        0.003418
24        0.003417
25        0.003416
26        0.003415
27        0.003414
28        0.003413
29        0.003412
            ...
249970    0.003857
249971    0.003856
249972    0.003855
249973    0.003854
249974    0.003853
249975    0.003852
249976    0.003851
249977    0.003850
249978    0.003849
249979    0.003848
249980    0.003847
249981    0.003846
249982    0.003845
249983    0.003844
249984    0.003843
249985    0.003842
249986    0.003841
249987    0.003840
249988    0.003839
249989    0.003838
249990    0.003837
249991    0.003836
249992    0.003835
249993    0.003834
249994    0.003833
249995    0.003832
249996    0.003831
249997    0.003829
249998    0.003828
249999    0.003827
Name: 0, Length: 250000, dtype: float64